### ISSUE TITLE
All fields are NULL if searching for series/TV show by ID

### ISSUE THREAD

**Issue by traubisoda** [chrisjp/IMDb-PHP-API#2]
If I try to pull series/TV show data by ID, all fields remain NULL

**Comment by chrisjp** [comment]
On line 22 of class_IMDb.php is an array of types to ignore: 
`public $ignoreTypes = array('tv_series','tv_special','video_game');`
If you remove tv_series and tv_special from this array it should return the data. If you've already done this and it's still returning NULL let me know and I'll look into it.

Sidenote: This is the default behaviour because the script was initially being used only for movies. Thinking about it now, it probably makes more sense to return data regardless of type, and leave it up to the end user to decide how they want to handle it... I will think of a better way to implement this in a future update.

**Comment by traubisoda** [comment]
Thank you for your fast reply, now it works like a charm! :)
Looking forward to future updates ;)
